name: Build
on: push

jobs:
  build:
    strategy:
      matrix:
        ros: [noetic]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.ros }}
          file: ${{ matrix.ros }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: atsushisaito/docker-ubuntu-sweb-ros:${{ matrix.ros }}
          cache-from: type=gha,scope=${{ matrix.ros }}
          cache-to: type=gha,mode=max,scope=${{ matrix.ros }}
          