name: Build
on: push

jobs:
  build:
    strategy:
      matrix:
        ros:
          [
            { code: noetic, version: base, fname: Base },
            { code: noetic, version: desktop, fname: Desktop },
            { code: noetic, version: desktop-full, fname: DesktopFull },
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Latest
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.ros.code }}
          file: ${{ matrix.ros.code }}/Dockerfile.${{ matrix.ros.fname }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            atsushisaito/docker-ubuntu-sweb:${{ matrix.ros.version }}
