name: Build
on: push

jobs:
  build:
    strategy:
      matrix:
        ros: [{ version: noetic, latest: true }]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        if: ${{ matrix.ros.latest == false }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.ros.version }}
          file: ${{ matrix.ros.version }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          cache-from: type=gha,scope=${{ matrix.ros.version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.ros.version }}
          tags: |
            atsushisaito/docker-ubuntu-sweb:${{ matrix.ros.version }}

      - name: Build and Push Latest
        if: ${{ matrix.ros.latest == true }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.ros.version }}
          file: ${{ matrix.ros.version }}/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          cache-from: type=gha,scope=${{ matrix.ros.version }}
          cache-to: type=gha,mode=max,scope=${{ matrix.ros.version }}
          tags: |
            atsushisaito/docker-ubuntu-sweb:${{ matrix.ros.version }}
            atsushisaito/docker-ubuntu-sweb:latest
